time:
  # 设定数据的规律
  time-fragment: "timestamp1"
  time-format: "millSeconds"
  time-start: 0
  time-end: 0
  time-duration: 7200
  time-interval: 60
  time-delta: 10
  count: -1
  realtime: true

data:
  fragments:
    # 数据都有哪些字段，格式 fragment: type
    content: "sentence"
    severity: "severity"
    type: "word"
    source: "word"
    host: "word"
    objectClass: "mul-word"
    object: "mul-word"
    parameter: "mul-word"
    cluster: "word"

output:
  # 数据的输出
  format: csv  # json, csv
  type: kafka
  file: ./output/result.csv
  bootstrap: "192.168.31.132:9092"
  topic: "autott1"
#  destination:
#    1:
#      format: transfer_to_json
#      type: file
#      path: ./output.transfer_to_json
#    2:
#      format: transfer_to_json
#      type: kafka
#      bootstrap-server: 192.168.31.132:9092
#      topic: auto-data
