time:
  # 设定数据的规律
  time-fragment: "eventTime"
  time-format: "millSeconds"
  time-start: 0
  time-end: 0
  time-duration: 7200
  time-interval: 60
  time-delta: 10
  count: -1
  realtime: true

data:
  fragments:
    # 数据都有哪些字段，格式 fragment: type
    content: "sentence"
    severity: "severity"
    source: "host"
    service: "service"
    objectClass: "objectClass"
    object: "oc_word"
    parameter: "parameter"
    cluster: "cluster"
    ext1: "word"
    扩展字段1扩展字段2扩展字段3扩展字段4扩展字段5扩展字段6: "word"
    ext2: "float"
    e4: "mul-word"
    extend frag 5: "word"

output:
  # 数据的输出
  format: csv  # json, csv
  type: kafka  # file, kafka, es
  # file
  file: ./output/result.json
  # kafka
  bootstrap: "192.168.31.132:9092"
  topic: "alert-silence"
  # elastic search
  es-hosts:
    - "192.168.21.92:9200"
  index: "es-index1"
  ################## end
