time:
  # 设定数据的规律
  time-fragment: "timestamp"
  time-format: "%Y-%m-%d"
  time-start: 0
  time-end: 0
  time-duration: 10
  time-interval: 1
  time-delta: 1

data:
  fragments:
    # 数据都有哪些字段，格式 fragment: type
    # 字符串数据类型 sentence, word, mul-word
    # 数字类型 int, float
    content: "sentence"
    severity: "int"
    type: "word"
    source: "word"
    host: "word"
    objectClass: "mul-word"
    object: "mul-word"
    parameter: "mul-word"
    cluster: "word"

output:
  # 数据的输出
  format: json  # json, xml
  type: file
  path: ../data/output.json
#  destination:
#    1:
#      format: json
#      type: file
#      path: ./output.json
#    2:
#      format: json
#      type: kafka
#      bootstrap-server: 192.168.31.132:9092
#      topic: auto-data
