time:
  # 设定数据的规律
  time-fragment: "timestamp"
  time-format: "%Y-%m-%d %H:%M:%S"
  time-start: 0
  time-end: 0
  time-duration: 7200
  time-interval: 60
  time-delta: 10
  count: -1
  realtime: true

data:
  fragments:
    # 数据都有哪些字段，格式 fragment: type
    content: "sentence"
    severity: "severity"
    type: "word"
    source: "word"
    host: "word"
    objectClass: "mul-word"
    object: "mul-word"
    parameter: "mul-word"
    cluster: "word"

output:
  # 数据的输出
  format: json  # json, xml
  type: json
  file: ./output/result.json
#  destination:
#    1:
#      format: to_json
#      type: file
#      path: ./output.to_json
#    2:
#      format: to_json
#      type: kafka
#      bootstrap-server: 192.168.31.132:9092
#      topic: auto-data
