time:
  # 设定数据的规律
  time-fragment: "eventTime"
  time-format: "%Y-%m-%d %H:%M:%S"
  time-start: 0
  time-end: 0
  time-duration: 7200
  time-interval: 60
  time-delta: 10
  count: -1
  # realtime: False

data:
  fragments:
    # 数据都有哪些字段，格式 fragment: type
    content: "sentence"
    severity: "severity"
    source: "host"
    service: "service"
    objectClass: "objectClass"
    object: "oc_word"
    parameter: "parameter"
    cluster: "cluster"
    ext1: "word"

output:
  # 数据的输出
  format: json # json, csv
  type: file  # file, kafka, es
  # file
  file: ./output/result.json
  # kafka
  bootstrap: "192.168.31.132:9092"
  topic: "alert-silence"
  # elastic search
  es-hosts:
    - "192.168.21.92:9200"
  index: "es-index1"
  ################## end
